### ISSUE TITLE
Número de telefone não está sendo salvo no banco de dados

### ISSUE THREAD

**Issue by Pedrolira16** [TheEuri/cesaride#18]
Ao tentar utilizar o telefone do usuário numa função, foi percebido que ele não estava aparecendo no site. Quando verificamos, o telefone não estava cadastrando no banco de dados. 

![image](https://github.com/TheEuri/cesaride/assets/134390540/a98f0d29-7c04-453c-83cd-a40c3a75e1f8)

![image](https://github.com/TheEuri/cesaride/assets/134390540/cba4c6d0-63c0-4399-b393-9c327a83f872)

![image](https://github.com/TheEuri/cesaride/assets/134390540/f3407ea6-def6-4669-997a-5ff9eb6ca86a)

**Comment by TheEuri** [comment]
Na views.py estava sendo passado apenas os campos de email, senha e usuário.

Para resolver o problema foi adicionado na função de cadastrar usuário os seguintes fragmentos de código:
```python
 phone_number = request.POST.get('phone_number')
 my_user = User.objects.create_user(username=username, email=email, password=pass1, phone_number=phone_number)

``` 

Bug resolvido no commit [f9a2c1b7c3936a60326b0d996bbf6b33e901e2cf](https://github.com/TheEuri/cesaride/commit/f9a2c1b7c3936a60326b0d996bbf6b33e901e2cf)
